<?php


namespace App\Models\CADECO;


class EmpresaFondoFijo extends Empresa
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(function ($query){
            return $query->where('tipo_empresa', '=', 32);
        });
    }
}