<?php
/**
 * Created by PhpStorm.
 * User: DBenitezc
 * Date: 20/08/2019
 * Time: 05:34 PM
 */

namespace App\Models\CADECO;


class EntradaAlmacenPartida extends Item
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(function ($query){
            return $query->whereHas('entrada')->where('estado', '>=', 0);
        });
    }

    public function entrada()
    {
        return $this->belongsTo(EntradaMaterial::class, 'id_transaccion', 'id_transaccion');
    }
}