<?php
/**
 * Created by PhpStorm.
 * User: DBenitezc
 * Date: 12/07/2019
 * Time: 01:25 PM
 */

namespace App\Models\CADECO;


class FacturaPartida extends Item
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(function ($query){
           return $query->whereHas('factura')->where('estado', '>=', 0);
        });
    }

    public function factura()
    {
        return $this->belongsTo(Factura::class, 'id_transaccion', 'id_transaccion');
    }
}