<?php
/**
 * Created by PhpStorm.
 * User: EMartinez
 * Date: 07/01/2020
 * Time: 09:42 PM
 */

namespace App\Models\CADECO;


class ItemOrdenPago extends Item
{
    protected $fillable = [
        'id_transaccion',
        'item_antecedente',
        'importe',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(function ($query) {
            return $query->whereHas('ordenPago');
        });
    }

    public function ordenPago(){
        return $this->belongsTo(OrdenPago::class, 'id_transaccion', 'id_transaccion');
    }

}