<?php

namespace App\Models\CADECO;


use mysql_xdevapi\Exception;
use App\Models\CADECO\AplicacionManual;

class ItemAplicacionManual extends Item
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(function ($query) {
            return $query->whereHas('aplicacionManual');
        });
    }

    public function aplicacionManual(){
        return $this->belongsTo(AplicacionManual::class, 'id_transaccion', 'id_transaccion');
    }
}