<?php

namespace App\Models\CADECO;


use App\Facades\Context;
use App\Models\CADECO\Compras\ItemContratista;
use Illuminate\Support\Facades\DB;

class ItemTransferenciaAlmacen extends Item
{
    protected $fillable = [
        'id_transaccion',
        'cantidad',
        'importe',
        'id_almacen',
        'id_concepto',
        'id_material',
        'unidad'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(function ($query) {
            return $query->whereHas('transferencia')->where('estado', '>=', 0);
        });
    }

    public function transferencia()
    {
        return $this->belongsTo(SalidaAlmacenTransferencia::class, 'id_transaccion', 'id_transaccion');
    }

}
