<?php
/**
 * Created by PhpStorm.
 * User: EMartinez
 * Date: 08/01/2020
 * Time: 05:06 PM
 */

namespace App\Models\CADECO;


class ItemListaRaya extends Item
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(function ($query) {
            return $query->whereHas('lista_raya');
        });
    }

    public function inventario()
    {
        return $this->hasOne(Inventario::class, 'id_item', 'id_item');
    }

    public function lista_raya()
    {
        return $this->belongsTo(ListaRaya::class, 'id_transaccion', 'id_transaccion');
    }
}
