<?php
/**
 * Created by PhpStorm.
 * User: DBenitezc
 * Date: 20/08/2019
 * Time: 05:49 PM
 */

namespace App\Models\CADECO;


class SalidaAlmacenPartida extends Item
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(function ($query){
            return $query->whereHas('salida')->where('estado', '>=', 0);
        });
    }

    public function salida()
    {
        return $this->belongsTo(SalidaAlmacen::class, 'id_transaccion', 'id_transaccion');
    }
}