<?php

namespace App\Exports\Contabilidad;

use App\Models\SEGURIDAD_ERP\Contabilidad\Empresa;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class LayoutPasivosIFSExport implements FromCollection, WithHeadings
{
    protected $pasivos;

    public function __construct($pasivos)
    {
        $this->pasivos = $pasivos;
    }

    public function collection()
    {
        $lista_pasivos = [];
        $i = 1;
        foreach ($this->pasivos as $pasivo) {
            if ($pasivo->cfdi) {
                $lista_pasivos[] = array(
                    'ID_COMPA' =>$pasivo->CFDI->rfc_receptor,
                    'LINE_TYPE' => "A",
                    'IDENTITY' => $pasivo->CFDI->rfc_emisor,
                    'INVOICE_NO' => $pasivo->CFDI->uuid,
                    'TRANSACTION_DATE' => $pasivo->CFDI->fecha_format,
                    'INVOICE_TYPE' => '',
                    'INVOICE_DATE' => $pasivo->CFDI->fecha_format,
                    'ARRIVAL_DATE' => '',
                    'DUE_DATE' => $pasivo->CFDI->fecha_format,
                    'PAY_TERM_ID' => 0,
                    'CURRENCY' => $pasivo->CFDI->moneda,
                    'CURR_RATE' => ($pasivo->CFDI->tipo_cambio == 0 || $pasivo->CFDI->tipo_cambio == 0)?1:$pasivo->CFDI->tipo_cambio,
                    'AUTH_ID' => "*",
                    'VOUCHER_TYPE' => '',
                    'VOUCHER_NO' => '',
                    'HTEXT' => '',
                    'PLAN_PAYMENT_DATE' => '',
                    'DIV_FACTOR' => $pasivo->CFDI->tipo_cambio,
                    'PRELIM_CODE' => '',
                    'NATIONAL_BANK_CODE' => '',
                    'CREATORS_REFERENCE' => '',
                    'PO_REFERENCE' => '',
                    'SERIES_REFERENCE' => '',
                    'NUMBER_REFERENCE' => '',
                    'DISCOUNT_DATE1' => '',
                    'DISCOUNT_PERC1' => '',
                    'DISCOUNT_DATE2' => '',
                    'DISCOUNT_PERC2' => '',
                    'DISCOUNT_DATE3' => '',
                    'DISCOUNT_PERC3' => '',
                    'PRE_ACC_CODE_B' => '',
                    'PRE_ACC_CODE_C' => '',
                    'PRE_ACC_CODE_D' => '',
                    'PRE_ACC_CODE_E' => $pasivo->CFDI->rfc_emisor,
                    'PRE_ACC_CODE_F' => '',
                    'PRE_ACC_CODE_G' => '',
                    'PRE_ACC_CODE_H' => '',
                    'PRE_ACC_CODE_I' => '',
                    'PRE_ACC_CODE_J' => '',
                    'SUPPLIER_ORDER_NO' => '',
                    'OUR_REFERENCE' => '',
                    'YOUR_REFERENCE' => '',
                    'DELIVERY_TERMS_DESC' => '',
                    'SHIP_VIA_DESC' => '',
                    'FORWARD_AGENT' => '',
                    'LABEL_NOTE' => '',
                    'ITEM_ID' => 1,
                    'VAT_CODE' => "IVA" . ($pasivo->CFDI->tasa_iva * 100),
                    'NET_CURR_AMOUNT' => $pasivo->CFDI->total,
                    'NET_DOM_AMOUNT' => $pasivo->CFDI->total_mxn,
                    'VAT_CURR_AMOUNT' => $pasivo->CFDI->importe_iva,
                    'VAT_DOM_AMOUNT' => $pasivo->CFDI->importe_iva_mxn,
                    'REFERENCE' => '',
                    'DELIV_TYPE_ID' => '',
                    'PO_ITEM_REF' => '',
                    'ITEM_POS' => '',
                    'PUR_PART_NO' => '',
                    'PUR_PART_DESC' => '',
                    'SUP_PART_NO' => '',
                    'SUP_PART_DESC' => '',
                    'INVOICED_QTY' => '',
                    'SALES_UM' => '',
                    'SALES_UNIT_PRICE' => '',
                    'PRICE_UM' => '',
                    'LINE_DISCOUNT' => '',
                    'ORDER_DISCOUNT' => '',
                    'TAX_ID' => ($pasivo->CFDI->tasa_iva * 100),
                    'TAX_PERCENTAGE' => '',
                    'TAX_CURR_AMOUNT' => $pasivo->CFDI->importe_iva,
                    'TAX_DOM_AMOUNT' => $pasivo->CFDI->importe_iva_mxn,
                    'FEE_CODE' => "IVA" . ($pasivo->CFDI->tasa_iva * 100),
                    'ROW_ID' => '1',
                    'CODE_A' => '0',
                    'CODE_B' => '',
                    'CODE_C' => '',
                    'CODE_D' => '',
                    'CODE_E' => $pasivo->CFDI->rfc_emisor,
                    'CODE_F' => '',
                    'CODE_G' => '',
                    'CODE_H' => '',
                    'CODE_I' => '',
                    'CODE_J' => '',
                    'QUANTITY' => '',
                    'CURR_AMOUNT' => $pasivo->saldo,
                    'DOM_AMOUNT' => $pasivo->saldo_mxn,
                    'AUTO_POSTING_PROC_CODE' => '',
                    'OPTIONAL_CODE' => '',
                    'TEXT' => '',
                    'PROJECT_ACTIVITY_ID' => '',
                    'PAYMENT_REFERENCE' => '',
                    'PRE_PROJECT_ACTIVITY_ID' => '',
                    'DISCOUNT_CURRAMOUNT1' => '',
                    'DISCOUNT_DOMAMOUNT1' => '',
                    'DISCOUNT_CURRAMOUNT2' => '',
                    'DISCOUNT_DOMAMOUNT2' => '',
                    'DISCOUNT_CURRAMOUNT3' => '',
                    'DISCOUNT_DOMAMOUNT3' => '',
                    'PAY_TERM_BASE_DATE' => '',
                    'GROSS_CURR_AMOUNT' => '',
                    'BATCH_ID' => '',
                    'CHARGE_AMOUNT' => '',
                    'CHARGE_TYPE' => '',
                    'BANK_ACCOUNT' => '',
                    'ADVANCE_INVOICE' => '',
                    'NATURE_OF_BUSINESS' => '',
                    'DELIVERY_DATE' => '',
                    'MAN_TAX_LIABILITY_DATE' => '',
                    'SUB_CON_REFERENCE' => '',
                    'ASSOCIATION_NO' => '',
                    'TAX_NUMBER' => $pasivo->CFDI->rfc_emisor,
                    'AFFECT_LINE_POSTINGS' => '',
                    'PROJECT_ID' => '',
                    'ADV_SERIES_ID' => '',
                    'ADV_INVOICE_NO' => '',
                    'AMORTIZED_AMOUNT' => '',
                    'EVENT_DATE' => '',
                    'RETROACTIVE_DATE' => '',
                    'TRANSACTION_REASON' => '',
                    'INCOME_TYPE_ID' => '',
                    'MULTIPLE_LINES_ALLOWED' => 'FALSE',
                    'UUID' => $pasivo->CFDI->uuid,
                );
                $i++;
            }
        }
        return collect($lista_pasivos);
    }


    /**
     * @return array
     */
    public function headings(): array
    {
        return [
            'ID_COMPA',
            'LINE_TYPE',
            'IDENTITY',
            'INVOICE_NO',
            'TRANSACTION_DATE',
            'INVOICE_TYPE',
            'INVOICE_DATE',
            'ARRIVAL_DATE',
            'DUE_DATE',
            'PAY_TERM_ID',
            'CURRENCY',
            'CURR_RATE',
            'AUTH_ID',
            'VOUCHER_TYPE',
            'VOUCHER_NO',
            'HTEXT',
            'PLAN_PAYMENT_DATE',
            'DIV_FACTOR',
            'PRELIM_CODE',
            'NATIONAL_BANK_CODE',
            'CREATORS_REFERENCE',
            'PO_REFERENCE',
            'SERIES_REFERENCE',
            'NUMBER_REFERENCE',
            'DISCOUNT_DATE1',
            'DISCOUNT_PERC1',
            'DISCOUNT_DATE2',
            'DISCOUNT_PERC2',
            'DISCOUNT_DATE3',
            'DISCOUNT_PERC3',
            'PRE_ACC_CODE_B',
            'PRE_ACC_CODE_C',
            'PRE_ACC_CODE_D',
            'PRE_ACC_CODE_E',
            'PRE_ACC_CODE_F',
            'PRE_ACC_CODE_G',
            'PRE_ACC_CODE_H',
            'PRE_ACC_CODE_I',
            'PRE_ACC_CODE_J',
            'SUPPLIER_ORDER_NO',
            'OUR_REFERENCE',
            'YOUR_REFERENCE',
            'DELIVERY_TERMS_DESC',
            'SHIP_VIA_DESC',
            'FORWARD_AGENT',
            'LABEL_NOTE',
            'ITEM_ID',
            'VAT_CODE',
            'NET_CURR_AMOUNT',
            'NET_DOM_AMOUNT',
            'VAT_CURR_AMOUNT',
            'VAT_DOM_AMOUNT',
            'REFERENCE',
            'DELIV_TYPE_ID',
            'PO_ITEM_REF',
            'ITEM_POS',
            'PUR_PART_NO',
            'PUR_PART_DESC',
            'SUP_PART_NO',
            'SUP_PART_DESC',
            'INVOICED_QTY',
            'SALES_UM',
            'SALES_UNIT_PRICE',
            'PRICE_UM',
            'LINE_DISCOUNT',
            'ORDER_DISCOUNT',
            'TAX_ID',
            'TAX_PERCENTAGE',
            'TAX_CURR_AMOUNT',
            'TAX_DOM_AMOUNT',
            'FEE_CODE',
            'ROW_ID',
            'CODE_A',
            'CODE_B',
            'CODE_C',
            'CODE_D',
            'CODE_E',
            'CODE_F',
            'CODE_G',
            'CODE_H',
            'CODE_I',
            'CODE_J',
            'QUANTITY',
            'CURR_AMOUNT',
            'DOM_AMOUNT',
            'AUTO_POSTING_PROC_CODE',
            'OPTIONAL_CODE',
            'TEXT',
            'PROJECT_ACTIVITY_ID',
            'PAYMENT_REFERENCE',
            'PRE_PROJECT_ACTIVITY_ID',
            'DISCOUNT_CURRAMOUNT1',
            'DISCOUNT_DOMAMOUNT1',
            'DISCOUNT_CURRAMOUNT2',
            'DISCOUNT_DOMAMOUNT2',
            'DISCOUNT_CURRAMOUNT3',
            'DISCOUNT_DOMAMOUNT3',
            'PAY_TERM_BASE_DATE',
            'GROSS_CURR_AMOUNT',
            'BATCH_ID',
            'CHARGE_AMOUNT',
            'CHARGE_TYPE',
            'BANK_ACCOUNT',
            'ADVANCE_INVOICE',
            'NATURE_OF_BUSINESS',
            'DELIVERY_DATE',
            'MAN_TAX_LIABILITY_DATE',
            'SUB_CON_REFERENCE',
            'ASSOCIATION_NO',
            'TAX_NUMBER',
            'AFFECT_LINE_POSTINGS',
            'PROJECT_ID',
            'ADV_SERIES_ID',
            'ADV_INVOICE_NO',
            'AMORTIZED_AMOUNT',
            'EVENT_DATE',
            'RETROACTIVE_DATE',
            'TRANSACTION_REASON',
            'INCOME_TYPE_ID',
            'MULTIPLE_LINES_ALLOWED',
            'UUID',
        ];
    }
}
