<?php
/**
 * Created by PhpStorm.
 * User: DBenitezc
 * Date: 23/05/2019
 * Time: 06:33 PM
 */

namespace App\Models\MODULOSSAO\Proyectos;

use App\Models\MODULOSSAO\Seguridad\Usuario;
use App\Models\MODULOSSAO\Seguridad\UsuarioProyecto;
use App\Models\MODULOSSAO\UnificacionObra;
use Illuminate\Database\Eloquent\Model;

class Proyecto extends Model
{
    protected $connection = 'modulosao';
    protected $table = 'Proyectos.Proyectos';
    protected $primaryKey = 'IDProyecto';
    public $timestamps = false;

    protected static  function  boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(function ($query){

        });
    }

    /**
     * Relaciones
     */
    public function proyectoUnificado(){
        return $this->belongsTo(ProyectoUnificado::class, 'IDProyecto', 'IDProyecto');
    }

    public function usuarioProyecto()
    {
        return $this->belongsTo(UsuarioProyecto::class, 'IDUsuario', 'IDUsuario');
    }

    /**
     * Scope
     */
    public function scopePorUsuario($query)
    {
        $usuario = Usuario::getUsuario()->first();
        if($usuario->AccesoTodosProyectos == 1)
        {
            return $query;
        }else {
            return $query->whereIn('IDProyecto',$usuario->usuarioProyectos->pluck('IDProyecto'));
        }
    }
}
