<?php
/**
 * Created by PhpStorm.
 * User: DBenitezc
 * Date: 23/05/2019
 * Time: 06:34 PM
 */

namespace App\Models\MODULOSSAO\Proyectos;


use App\Models\MODULOSSAO\BaseDatos\BaseDato;
use Illuminate\Database\Eloquent\Model;

class ProyectoUnificado extends Model
{
    protected $connection = 'modulosao';
    protected $table = 'Proyectos.ProyectosUnificados';
    protected $primaryKey = 'IDProyectoUnificado';
    public $timestamps = false;

    protected static  function  boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(function ($query){
            return $query->has('base');
        });
    }

    public function proyectos(){
        return $this->belongsTo(Proyecto::class, 'IDProyecto', 'IDProyecto');
    }

    public function base(){
        return $this->belongsTo(BaseDato::class, 'IDBaseDatos', 'IDBaseDatos');
    }
}