<?php
/**
 * Created by PhpStorm.
 * User: DBenitezc
 * Date: 14/08/2019
 * Time: 10:40 AM
 */

namespace App\Models\CADECO\FinanzasCBE;


use App\Models\CADECO\Finanzas\CuentaBancariaEmpresa;
use Illuminate\Support\Facades\DB;

class SolicitudBaja extends Solicitud
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(function ($query) {
            return $query->where('id_tipo_solicitud', '=', 2);
        });

        self::creating(function ($solicitud){
            $solicitud->validar();
            $solicitud->numero_folio = $solicitud->folio();
            $solicitud->id_tipo_solicitud = 2;
            $solicitud->fecha = date('Y-m-d H:i:s');
            $solicitud->usuario_registra = auth()->id();
            $solicitud->estado = 1;
        });

        self::created(function ($sol){
            $sol->generaMovimiento(1);
        });
    }

    private function validar()
    {
        if(CuentaBancariaEmpresa::query()->where('id_empresa', '=', $this->id_empresa)->where('cuenta_clabe', '=', $this->cuenta_clabe)->where('estatus','>=',0)->get()->toArray() == [])
        {
            abort(400, 'No existe está baja bancaria empresa.');
        }

        if(SolicitudBaja::query()->where('cuenta_clabe', $this->cuenta_clabe)->where('id_empresa', '=', $this->id_empresa)->where('estado','>=',0)->get()->toArray() != [])
        {
            abort(400, 'Ya existe una solicitud de baja para está cuenta bancaria.');
        }
    }

    /**
     * @return mixed
     */
    public function generaMovimiento($tipo_movimiento)
    {
        return SolicitudMovimiento::create([
                'id_solicitud'=>$this->id,
                'id_tipo_movimiento'=>$tipo_movimiento,
                'observaciones'=>$this->observaciones
            ]
        );
    }

    /**
     * @return int
     */
    public function folio()
    {
        return $count = SolicitudBaja::query()->count('id') + 1;
    }

    public function autorizar()
    {
        DB::connection('cadeco')->transaction(function() {
            $cuenta_empresa = CuentaBancariaEmpresa::query()->where('id', $this->id_cuenta);

            if ($cuenta_empresa->get()->toArray() == []) {
                abort(400, 'No se encuentra está cuenta bancaria empresa.');
            }
            if ($cuenta_empresa->get()->toArray()[0]['estatus'] <= 0) {
                abort(400, 'Está Cuenta Bancaria se dio de baja previamente.');
            }

            $cuenta_empresa->update([
                'id_solicitud_origen_baja' => $this->id,
                'estatus' => -1
            ]);

            $movimiento = SolicitudMovimiento::query()->where('id_solicitud', '=', $this->id)->first();

            $movs = SolicitudMovimiento::query()->create([
                'id_solicitud' => $this->id,
                'id_movimiento_antecedente' => $movimiento->id,
                'id_tipo_movimiento' => 2,
            ]);

            $this->update([
                'estado' => 2
            ]);
        });
        return $this;
    }
}