<?php
/**
 * Created by PhpStorm.
 * User: DBenitezc
 * Date: 23/05/2019
 * Time: 06:32 PM
 */

namespace App\Models\MODULOSSAO\ControlRemesas;


use App\Models\CADECO\Cambio;
use App\Models\CADECO\Empresa;
use App\Models\CADECO\Finanzas\DistribucionRecursoRemesaPartida;
use Illuminate\Database\Eloquent\Model;

class Documento extends Model
{
    protected $connection = 'modulosao';
    protected $table = 'ControlRemesas.Documentos';
    protected $primaryKey = 'IDDocumento';
    public $timestamps = false;

    protected $hidden = ['disponible'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(function ($query){
            return $query->has('documentoLiberado');
        });
    }

    public function remesa(){
        return $this->hasMany(Remesa::class, 'IDRemesa', 'IDRemesa');
    }

    public function documentoLiberado()
    {
        return $this->belongsTo(DocumentoLiberado::class, 'IDDocumento', 'IDDocumento');
    }

    public function partidas(){
        return $this->belongsTo(DistribucionRecursoRemesaPartida::class, 'IDDocumento', 'id_documento');
    }

    public function empresa()
    {
        return $this->belongsTo(Empresa::class, 'IDDestinatario', 'id_empresa');
    }

    public function tipoCambio()
    {
        return $this->belongsTo(Cambio::class, 'IDMoneda', 'id_moneda');
    }

    public function getDisponibleAttribute()
    {
        $existente = DistribucionRecursoRemesaPartida::query()->select('id_documento')->where('id_documento', '=', $this->IDDocumento)->where('estado', '!=', 3)->get()->toArray();

        if ($existente != []) {
            return 0;
        }else{
            return 1;
        }
    }
}