<?php


namespace App\Models\MODULOSSAO\ControlRemesas;


use App\Models\MODULOSSAO\BaseDatosObra;
use App\Models\MODULOSSAO\Proyectos\Proyecto;
use Illuminate\Database\Eloquent\Model;

class RemesaFolio extends Model
{
    protected $connection = 'modulosao';
    protected $table = 'ControlRemesas.RemesasFolios';
    public $timestamps = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(function ($query){
            $proyectos = Proyecto::porUsuario()->orderBy('Nombre')->pluck('IdProyecto');
            return $query->whereIn('IDProyecto', $proyectos);
        });
    }

    /**
     * Relaciones
     */
    public function proyecto()
    {
        return $this->hasOne(Proyecto::class, 'IDProyecto', 'IDProyecto');
    }

    /**
     * Scope
     */
    public function scopeOrdenarPorAnioSemana($query)
    {
        return $query->orderBy('Anio','desc')->orderBy('NumeroSemana','desc');
    }

    /**
     * Atributos
     */
    public function getNombreProyectoAttribute()
    {
        try{
            return $this->proyecto->Nombre;
        }catch (\Exception $e){
            return null;
        }
    }

    /**
     * Métodos
     */
    public function validarEdicion()
    {
        dd("validar aqui");
    }
}
