<?php


namespace App\Models\SEGURIDAD_ERP\Compras;


use App\Facades\Context;
use Illuminate\Database\Eloquent\Model;

class Configuracion extends Model
{
    protected $connection = 'seguridad';
    protected $table = 'Compras.configuracion';

    protected static  function  boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(function ($query){
            return $query->join('proyectos', 'proyectos.id', 'configuracion.id_proyecto')
                ->where('proyectos.base_datos', Context::getDatabase());
        });
    }

    public function obra()
    {
        return $this->belongsTo(Obra::class, 'id_obra');
    }

}
