<?php
/**
 * Created by PhpStorm.
 * User: JLopezA
 * Date: 12/03/2020
 * Time: 09:00 PM
 */

namespace App\Models\CADECO\ControlPresupuesto;

use App\Models\CADECO\Concepto;

// use Illuminate\Database\Eloquent\Model;

class ExtraordinarioPartidas extends SolicitudCambioPartidas
{

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(function ($query) {
            return $query->whereHas('solicitudcambio')->where('id_tipo_orden', '=', 4);
        });
    }

    public function concepto(){
        return $this->belongsTo(Concepto::class, 'id_concepto', 'id_concepto');
    }



    public function getImporteCambioFormatAttribute(){
        return '$' . number_format(($this->precio_unitario_original * $this->variacion_volumen), 2, '.',',');
    }

    public function getImporteActualizadoFormatAttribute(){
        return '$' . number_format(($this->precio_unitario_original * $this->cantidad_presupuestada_nueva), 2, '.',',');
    }

    public function getVariacionVolumenFormatAttribute(){
        return number_format($this->variacion_volumen, 4, '.', '');
    }

    public function getDescripcionFormatAttribute(){
        return substr($this->concepto->descripcion, 0, 35);
    }

}
